spring.application.name=my-cart

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

project.image=images/

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpirationMs=300000000
spring.ecom.app.jwtCookieName=springBootEcom

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.ecommerce.project=DEBUG


# Needed if you are using elastic beanstalk
server.port=5000
frontend.url=http://localhost:5173/
image.base.url=http://localhost:5000/images

#STRIPE KEY
stripe.secret.key=${STRIPE_SECRET_KEY}